artifacts_root: artifacts

data_ingestion:
  source_url: 'https://drive.google.com/file/d/1lmKT53zineb3yVrAIlcQa8Mksg5oL2ig/view?usp=drive_link'
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts/data
  data_path: artifacts/data/fraud.csv
  train_path: artifacts/data/train.csv
  test_path: artifacts/data/test.csv

data_transformation:
  root_dir: artifacts/preprocess
  preprocessor_path: artifacts/preprocess/preprocessor.pkl
  train_path: artifacts/data/train.csv
  train_arr: artifacts/preprocess/train_array.npy
  test_path: artifacts/data/test.csv
  test_arr: artifacts/preprocess/test_array.npy

model_training:
  root_dir: artifacts/models
  result_dir: artifacts/results
  model_path: artifacts/models/model.pkl
  train_arr: artifacts/preprocess/train_array.npy
  test_arr: artifacts/preprocess/test_array.npy
  train_result: artifacts/results/train_result.json
  test_result: artifacts/results/test_result.json